feat(bulkmetadata): add StaticMetadata component
Amsterdam/bmi-dms-upload pull request #18
Opened 2021-11-30 11:24 UTC by johan-hage

2021-11-30 16:28 UTC, johan-hage commented on src/components/StaticMetadata/StaticMetadata.test.tsx
> +			if (typeof metadata.value === 'string') {
As we only render string values for the POC I ommited the Tag render testcase. If there is a wise solution available to check in the test if metadata.value is a type of React.ReactNode andso test the existence of the Tag output, glad to hear :-)

2021-12-01 18:26 UTC, fortunato commented on src/components/StaticMetadata/StaticMetadata.test.tsx
> +			if (typeof metadata.value === 'string') {
You can mock `<Tag />` and spy on the mock being called with the appropriate props. Arguably though you only have to mock the description list component and check for the props on that. Coverage on the internals of the description list exist in the component library already.

2021-12-01 18:36 UTC, fortunato requested changes
Looks good mostly :ok_hand:

2021-12-01 18:36 UTC, fortunato commented on src/components/StaticMetadata/__stubs__/metadataList.tsx
> +export const metadataList: DescriptionList = [
I'm confused about this not throwing an error :thinking: 
I believe the appropriate type would be `ComponentProps<typeof DescriptionList>['list']`

2021-12-01 18:36 UTC, fortunato commented on src/components/StaticMetadata/StaticMetadata.stories.mdx
> +import { Meta, Story, Canvas } from '@storybook/addon-docs'
Please convert this to .tsx so that we can enjoy type safety in storybook as well.

2021-12-03 10:55 UTC, johan-hage commented on src/components/StaticMetadata/StaticMetadata.test.tsx
> +			if (typeof metadata.value === 'string') {
Changed.

2021-12-06 08:44 UTC, johan-hage reviewed
Updated by review comments.

2021-12-08 09:22 UTC, fortunato approved these changes
:clap: nicely done

2021-12-08 09:22 UTC, fortunato commented on src/components/StaticMetadata/StaticMetadata.test.tsx
> +describe('<StaticMetadata />', () => {
Neat :ok_hand:

2021-12-08 09:46 UTC, merged